fix workflow

diff --git a/.github/workflows/read-version-node-test.yml b/.github/workflows/read-version-node-test.yml
--- a/.github/workflows/read-version-node-test.yml
+++ b/.github/workflows/read-version-node-test.yml
@@ -7,24 +7,17 @@ on:
       - ".github/workflows/read-version-node-test.yml"
 
 jobs:
-  prepare:
-    runs-on: ubuntu-latest
-    outputs:
-      package_json: ${{ steps.put_package_json.outputs.package_json }}
-    steps:
-      - name: "Prepare package.json"
-        id: put_package_json
-        run: |
-          echo '{ "version": "0.0.1" }' > package.json
-          echo "::set-output name=package_json::\"$(cat package.json)\""
   invoke:
     needs: prepare
     uses: Devecorsoft/workflows/.github/workflows/read-version-node.yml@v1
     with:
-      package_json: ${{ needs.prepare.outputs.package_json }}
+      package_json: "./test/package.json"
   assert:
     runs-on: ubuntu-latest
     needs:
       - invoke
     steps:
-      - run: echo "${{ needs.invoke.outputs.version }}"
+      - if: ${{ needs.invoke.outputs.version != '1.0.0' }}
+        run: |
+          echo "Failed!"
+          exit 1
